import { RetryStatus } from './RetryStatus';
import { RoundFailure } from './RoundFailure';
import { useState, useMemo, useEffect } from 'react';
import { Play, Square, FlaskConical, Bot, ArrowUpRight, FileCode2, Target, CheckCircle2, Clock3, ChevronRight, Search, Settings2 } from 'lucide-react';
import type { Config, Snapshot, LogEvent } from '@/lib/types';
import { metrics, percent, delta } from '@/lib/metrics';
import { BentoGrid, BentoGridItem } from './ui/bento-grid';
import { AnimatePresence, motion } from 'motion/react';
import { RoundRecords } from './RoundRecords';
import { RunningWave } from './RuntimeDock';
const statusNames:Record<string,string>={idle:'等待开始',running:'执行中',stopping:'停止中',completed:'已完成',failed:'执行失败',limited:'达到轮数上限',cancelled:'已停止',interrupted:'意外中断'};
export function Status({value}:{value:string}) {return <span className={'status '+value}><span/>{statusNames[value]??value}</span>;}
export function Dashboard({config,snapshot,onStart,onStop,onConfigureAgent,busy,notify,historical}:{config:Config;snapshot:Snapshot;logs:LogEvent[];onStart:(mode:string)=>Promise<void>;onStop:(mode?:'immediate'|'after-round')=>Promise<void>;onConfigureAgent:()=>void;busy:boolean;notify:(s:string)=>void;historical:boolean}) {
  const [selected,setSelected]=useState<number|null>(null);
  const [classesOpen,setClassesOpen]=useState(true);
  const [search,setSearch]=useState('');
  useEffect(()=>setSelected(null),[snapshot.id]);
  const rounds=snapshot.rounds??[];
  const round=selected==null?rounds.at(-1):rounds.find(r=>r.round===selected);
  const index=rounds.findIndex(r=>r.round===round?.round),previous=index>0?rounds[index-1]:undefined;
  const current=metrics(round),before=metrics(previous);
  const allClasses=round?.coverage.flatMap(m=>m.classes)??[];
  const newSatisfied=previous&&current.verified&&before.verified?allClasses.filter(c=>c.lineCoverage!=null&&c.lineCoverage>=config.coverage.lineThreshold&&previous.groups.pending.some(p=>p.modulePath===c.modulePath&&p.qualifiedName===c.qualifiedName)).length:null;
  const rows=useMemo(()=>allClasses.filter(c=>(c.lineCoverage??0)<config.coverage.lineThreshold&&c.qualifiedName.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.lineCoverage??0)-(b.lineCoverage??0)),[round,search,config.coverage.lineThreshold]);
  const action=(f:()=>Promise<void>)=>void f().catch(e=>notify(e instanceof Error?e.message:String(e)));
  const cards=[
    {title:'行覆盖率',value:percent(current.coverage),note:previous&&current.coverage!=null&&before.coverage!=null?delta(Number((current.coverage-before.coverage).toFixed(1)))+' 个百分点 / 较上一轮':'目标 '+config.coverage.lineThreshold+'%',icon:<Target size={17}/>},
    {title:'未达标类',value:round&&!current.invalid?String(current.pending):'—',note:current.invalid?current.classes+' 个类待评估':round?'所选范围共 '+current.classes+' 个类':'完成基线后统计',icon:<FileCode2 size={17}/>},
    {title:'单元测试 · DT',value:round?String(current.tests):'—',note:previous?'执行 DT 变化 '+delta(current.tests-before.tests):round?'其中失败 / 错误 '+current.failedTests:'来自 Surefire 实际执行结果',icon:<FlaskConical size={17}/>},
    {title:'本轮新达标',value:newSatisfied==null?'—':String(newSatisfied),note:previous?'上一轮未达标、本轮达标的类':'第一轮建立基线',icon:<CheckCircle2 size={17}/>},
  ];
  return <section className="dashboard"><div className="page-title"><div><div className="eyebrow">COVERAGE WORKBENCH{historical?' / HISTORY':''}</div><h1>{historical?'回看每一次进展':'让每一轮补测，都有迹可循。'}</h1><p>{config.selectedModulePaths.length} 个模块 · 每批 {config.agent.batchSize} 个类 · {config.agent.runUntilTarget!==false?'持续运行直到达标':`最多 ${config.agent.maxRounds} 轮验证`}</p></div><div className="button-group">{busy?<>{snapshot.mode==='loop'&&<button className="secondary" disabled={snapshot.status==='stopping'||snapshot.stopAfterRoundRequested} onClick={()=>action(()=>onStop('after-round'))}><Clock3 size={14}/>{snapshot.stopAfterRoundRequested?'已请求本轮后停止':'当前轮结束后停止'}</button>}<button className="danger" disabled={snapshot.status==='stopping'} onClick={()=>action(()=>onStop('immediate'))}><Square size={14}/>立即停止</button></>:!historical&&<><button className="secondary" onClick={()=>action(()=>onStart('baseline'))}><FlaskConical size={16}/>运行基线</button><button className="primary" onClick={config.agent.enabled?()=>action(()=>onStart('loop')):onConfigureAgent}>{config.agent.enabled?<Play size={15}/>:<Settings2 size={15}/>}{config.agent.enabled?'开始补测':'配置 Agent 后补测'}</button></>}</div></div>
    {!busy&&!historical&&!config.agent.enabled&&<div className="inline-note agent-setup-note" role="status"><Bot size={16}/><p>自动补测尚未启用。运行基线无需 Agent；点击“配置 Agent 后补测”，开启“启用自动补测”并保存，即可开始。</p></div>}
    <div className={"run-banner showcase-banner "+(busy?"is-active":"")}><div className={'run-symbol '+(busy?'pulse':'')}><Bot size={22}/>{busy&&<span className="orbit-ring"/>}</div><div><strong>{(busy&&snapshot.status!=='stopping'?snapshot.progress?.message:undefined)||snapshot.message||'工作区已准备就绪'}</strong><p>{round?'第 '+round.round+' 轮验证 · '+new Date(round.finishedAt).toLocaleTimeString():'先运行基线，了解当前测试与覆盖率情况。'}</p></div><Status value={snapshot.status}/>{!busy&&!historical&&<button className="ghost small" onClick={()=>action(()=>onStart('probe'))}>检查 Agent<ArrowUpRight size={14}/></button>}</div>
    {busy&&<div className="phase-ribbon"><RunningWave running/><span>{snapshot.progress?.modules?.filter(m=>m.status==='running').map(m=>`${m.name} · ${m.stage}`).join(' / ')||'执行状态持续更新中'}</span><small>展开底部控制台，查看各模块进度</small></div>}
    {snapshot.status==='running'&&<RetryStatus progress={snapshot.progress} stopAfterRound={snapshot.stopAfterRoundRequested}/>}
    <RoundFailure round={round}/><BentoGrid className="metrics-grid max-w-none md:auto-rows-auto md:grid-cols-4">{cards.map((c,i)=><motion.div key={c.title} className="metric-reveal" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:i*.06,duration:.35}}><BentoGridItem title={c.title} description={c.note} icon={c.icon} header={<div className="metric-value">{c.value}</div>} className="metric-card"/></motion.div>)}</BentoGrid>
    <div className="round-layout"><div className="panel trend-panel"><div className="section-heading"><div><h2>覆盖率走势</h2><p>每一轮都以真实 Maven 结果重新验证</p></div><span className="chart-legend"><span/>行覆盖率</span></div>{rounds.length?<div className="trend-chart"><div className="chart-axis"><span>100%</span><span>50%</span><span>0%</span></div><div className="chart-plot"><div className="chart-gridline top"/><div className="chart-gridline mid"/><div className="chart-target" style={{bottom:config.coverage.lineThreshold+'%'}}><span>目标 {config.coverage.lineThreshold}%</span></div><div className="chart-columns">{rounds.map(r=>{const m=metrics(r);return <button key={r.round} className={'chart-column '+(round?.round===r.round?'active':'')} onClick={()=>setSelected(r.round)} title={'第 '+r.round+' 轮 '+percent(m.coverage)}><span className="bar-value" style={{bottom:`calc(${m.coverage??0}% + 6px)`}}>{percent(m.coverage)}</span><motion.span className="bar" initial={{height:0}} animate={{height:(m.coverage??1)+'%'}} transition={{duration:.7,ease:'easeOut'}}/><span className="bar-label">R{String(r.round).padStart(2,'0')}</span></button>;})}</div></div></div>:<div className="chart-empty"><div className="empty-bars"><i/><i/><i/><i/><i/></div><p>你的第一条覆盖率曲线，从基线开始。</p></div>}</div>
      <div className="panel session-panel"><h2>执行概况</h2><div className="session-row"><span>编码助手</span><strong>{config.agent.provider==='hermes'?'Hermes':'OpenCode'}</strong></div><div className="session-row"><span>测试通过</span><strong>{round?Math.max(0,current.tests-current.failedTests-round.tests.skipped):'—'}</strong></div><div className="session-row"><span>失败 / 错误</span><strong className={current.failedTests?'error-text':''}>{round?current.failedTests:'—'}</strong></div><div className="session-row"><span>跳过测试</span><strong>{round?round.tests.skipped:'—'}</strong></div><div className="session-row"><span>数据来源</span><strong>{round?(current.invalid?'本轮构建未完成':current.verified?'本轮 JaCoCo':'部分未测 / 无测试'):'等待运行'}</strong></div><div className="session-foot"><Clock3 size={14}/>{snapshot.startedAt?new Date(snapshot.startedAt).toLocaleString():'任务尚未开始'}</div></div></div>
    <div className="panel rounds-panel"><div className="section-heading"><div><h2>逐轮记录 <span className="count-pill">{rounds.length}</span></h2><p>点击一轮，查看当时的未达标类和测试结果。</p></div>{selected!=null&&<button className="ghost small" onClick={()=>setSelected(null)}>跟随最新轮次<ChevronRight size={14}/></button>}</div><div className="table-scroll"><table><thead><tr><th>验证轮次</th><th>DT 总数</th><th>DT 变化</th><th>改动测试文件</th><th>失败 / 错误</th><th>未达标类</th><th>行覆盖率</th><th>变化</th><th>结果</th></tr></thead><tbody>{rounds.map((r,i)=>{const m=metrics(r),p=metrics(rounds[i-1]);return <tr key={r.round} className={round?.round===r.round?'selected':''} onClick={()=>setSelected(r.round)}><td><button className="round-link">R{String(r.round).padStart(2,'0')}{i===0&&<span className="subtle-badge">基线</span>}</button></td><td>{m.tests}</td><td className="accent">{i&&!m.invalid&&!p.invalid?delta(m.tests-p.tests):'—'}</td><td>{snapshot.agentRounds?.find(a=>a.round===r.round-1)?.changedTestFiles.length??'—'}</td><td className={m.failedTests?'error-text':''}>{m.failedTests}</td><td>{m.invalid?'未评估':m.pending}</td><td>{percent(m.coverage)}</td><td className="accent">{i&&m.coverage!=null&&p.coverage!=null?delta(Number((m.coverage-p.coverage).toFixed(1)))+' pp':'—'}</td><td><span className={'result-dot '+(r.exitCode===0&&m.failedTests===0?(m.verified?'ok':'unmeasured'):'bad')}/>{m.invalid?'构建未完成':r.exitCode===0&&m.failedTests===0?(m.verified?'验证通过':'含未测模块'):'需修复'}</td></tr>;})}{!rounds.length&&<tr><td colSpan={9} className="empty-cell">运行基线后，每轮的测试和覆盖率数据将自动记录在这里。</td></tr>}</tbody></table></div></div>
    <div className="panel detail-panel classes-panel"><div className="detail-toolbar"><button className="classes-disclosure" aria-expanded={classesOpen} aria-controls="pending-classes" onClick={()=>setClassesOpen(v=>!v)}><motion.span animate={{rotate:classesOpen?90:0}}><ChevronRight size={16}/></motion.span><FileCode2 size={15}/><strong>{current.invalid?'待评估类':'未达标类'}{round?' · R'+String(round.round).padStart(2,'0'):''}</strong><span className="count-pill">{rows.length}</span></button><label className="search compact-search"><Search size={14}/><input aria-label="搜索未达标类" placeholder="筛选类名…" value={search} onChange={e=>{setSearch(e.target.value);setClassesOpen(true);}}/></label></div>
    <AnimatePresence initial={false}>{classesOpen&&<motion.div id="pending-classes" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.25,ease:'easeInOut'}} className="collapsible-content"><div className="table-scroll"><table><thead><tr><th>类</th><th>模块</th><th>行覆盖率</th><th>未覆盖行</th><th>距目标</th></tr></thead><tbody>{rows.slice(0,300).map(c=>{const measured=!current.invalid&&round?.coverage.find(m=>m.modulePath===c.modulePath)?.source==='jacoco';return <tr key={c.modulePath+c.qualifiedName}><td><strong className="class-name">{c.className}</strong><small className="package-name">{c.packageName}</small></td><td><code>{c.modulePath}</code></td><td><div className="coverage-cell"><span>{measured?percent(c.lineCoverage):'未测量'}</span><div className="mini-track"><i style={{width:measured?(c.lineCoverage??0)+'%':'0%'}}/></div></div></td><td>{measured?c.missedLines:'—'}</td><td>{measured?Math.max(0,config.coverage.lineThreshold-(c.lineCoverage??0)).toFixed(1)+' pp':'—'}</td></tr>;})}{!rows.length&&<tr><td colSpan={5} className="empty-cell">{!round?'等待基线结果':search?'没有匹配的类':current.invalid?'构建未完成，无法判断是否达标':current.pending===0?'当前范围内没有未达标类':'当前轮未返回可展示的类数据'}</td></tr>}</tbody></table>{rows.length>300&&<p className="inline-note">显示前 300 个类，使用搜索定位其余类。</p>}</div></motion.div>}</AnimatePresence>
    </div><RoundRecords rootPomPath={config.rootPomPath} jobId={snapshot.id} round={round} busy={busy} notify={notify}/>
    <p className="metrics-note">DT 按 Surefire 执行用例计数，参数化测试可能计为多条；“DT 变化”是相邻轮次执行数量之差，不等同于新增测试方法数。缺少有效报告时不显示覆盖率。</p>
  </section>;
}
