import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { FileJson, FileText, FolderOpen, Terminal, RotateCcw, Copy, ExternalLink, LoaderCircle, ArrowUpRight } from 'lucide-react';
import { api } from '@/lib/api';
import type { Round, RoundRecordsData } from '@/lib/types';
import { HoverBorderGradient } from './ui/hover-border-gradient';

export function RoundRecords({rootPomPath,jobId,round,busy,notify}:{rootPomPath:string;jobId:string;round?:Round;busy:boolean;notify:(s:string)=>void}) {
  const [data,setData]=useState<RoundRecordsData|null>(null),[name,setName]=useState('coverage.json'),[content,setContent]=useState(''),[truncated,setTruncated]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false),[recovering,setRecovering]=useState(false);
  const number=round?.round;
  useEffect(()=>{setData(null);setError('');if(!number||!jobId)return;let alive=true;api.request<RoundRecordsData>('/round/records',{rootPomPath,id:jobId,round:number}).then(r=>{if(alive)setData(r);}).catch(e=>{if(alive)setError(String(e));});return()=>{alive=false;};},[rootPomPath,jobId,number,busy]);
  useEffect(()=>{setContent('');setTruncated(false);if(!number||!jobId||!data)return;let alive=true;setLoading(true);api.request<{content:string;truncated:boolean}>('/round/file',{rootPomPath,id:jobId,round:number,name}).then(r=>{if(alive){setContent(r.content||(name==='failed-classes.txt'?'本轮未达标类清单为空。':'（空文件）'));setTruncated(r.truncated);}}).catch(e=>{if(alive)setContent('读取失败：'+String(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[rootPomPath,jobId,number,name,data]);
  const recovery=data?.recovery,file=data?.files.find(f=>f.name===name);
  const recover=async()=>{if(!number)return;setRecovering(true);try{const r=await api.recoverSession({rootPomPath,id:jobId,round:number});notify('已打开恢复终端 · '+r.sessionId);}catch(e){notify(String(e));}finally{setRecovering(false);}};
  const run=(f:()=>Promise<unknown>)=>void f().catch(e=>notify(String(e)));
  return <section className="panel round-records" aria-label="打开本轮记录"><div className="record-heading"><div className="record-title"><span className="record-icon"><FolderOpen size={18}/></span><div><h2>打开本轮记录 {number&&<span className="count-pill">R{String(number).padStart(2,'0')}</span>}</h2><p>覆盖率、门禁与执行证据，保留每一步。</p></div></div><div className="button-group">{data&&<button className="ghost small" onClick={()=>run(()=>api.openArtifact(data.directory))}><ExternalLink size={13}/>打开目录</button>}{round?.finishedAt&&<HoverBorderGradient disabled={busy||recovering||!recovery?.available} onClick={()=>void recover()} containerClassName="recover-gradient" className="gradient-content" title={busy?'请先等待当前任务结束':recovery?.reason??'在命令行继续本轮关联的 Agent 会话'}><RotateCcw size={14} className={recovering?'spin':''}/>Recover session<ArrowUpRight size={13}/></HoverBorderGradient>}</div></div>
    {!round?<div className="record-empty"><FileJson size={28}/><strong>每一轮，都有完整的证据。</strong><p>运行结束后，选择一轮即可在这里查看六种记录文件。</p></div>:error?<div className="record-empty" role="alert">{error}</div>:!data?<div className="record-empty"><LoaderCircle className="spin" size={20}/>正在读取本轮记录…</div>:<>
    <div className="record-tabs" role="tablist" aria-label="本轮记录文件">{data.files.map(f=><button key={f.name} role="tab" aria-selected={name===f.name} aria-controls="record-content" className={name===f.name?'active':''} onClick={()=>setName(f.name)}>{f.name.endsWith('.json')?<FileJson size={14}/>:f.name.endsWith('.log')?<Terminal size={14}/>:<FileText size={14}/>}<span>{f.name}</span>{!f.exists&&<i title="本轮未生成"/>}{name===f.name&&<motion.span layoutId="record-tab-indicator" className="record-tab-indicator"/>}</button>)}</div>
    <div className="record-file-meta"><code title={file?.path}>{file?.path.split(/[/\\]/).at(-1)}</code><span>{file?.exists?file.size<1024?`${file.size} B`:`${(file.size/1024).toFixed(1)} KB`:'未生成'}</span><button className="icon-button" aria-label="复制文件内容" disabled={!content||loading} onClick={()=>run(async()=>{await navigator.clipboard.writeText(content);notify('文件内容已复制');})}><Copy size={13}/></button></div>
    <div className="record-viewer" id="record-content" role="tabpanel" aria-label={name} aria-busy={loading}><AnimatePresence mode="wait" initial={false}><motion.pre key={name+number+jobId} initial={{opacity:0,x:6}} animate={{opacity:1,x:0}} exit={{opacity:0}} transition={{duration:.14}}>{loading?'正在读取…':content.replace(/\u001b\[[0-?]*[ -/]*[@-~]/g,'')}</motion.pre></AnimatePresence></div>
    <div className="record-footnote"><span>{truncated?'显示前 512 KB；可打开目录查看完整文件。':'本轮文件 · 不随实时日志滚动'}</span><span>{recovery?.available?`恢复 ${recovery.provider} · R${String(recovery.originRound).padStart(2,'0')} 的会话 ${recovery.sessionId}`:recovery?.reason}</span></div></>}
  </section>;
}
