import { MavenVersionFields, type MavenVersionSettings } from './MavenVersionFields';
import { useState, useEffect } from 'react';
import { ArrowRight, ArrowLeft, FolderOpen, FileCog, Check, SlidersHorizontal, Code2, Save, Bot, Layers3 } from 'lucide-react';
import { motion } from 'motion/react';
import { api } from '@/lib/api';
import type { OpenProject, Config, PathKind, RecentProject } from '@/lib/types';
import { ScopeTree, selectedClassCount } from './ScopeTree';
import { HoverBorderGradient } from './ui/hover-border-gradient';

export function PathField({label,value,onChange,kind,placeholder,hint}:{label:string;value:string;onChange:(s:string)=>void;kind:PathKind;placeholder?:string;hint?:string}) {
  const [error,setError]=useState('');
  return <label className="field"><span>{label}</span><div className="path-input"><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><button type="button" className="icon-button" aria-label={'选择'+label} onClick={async()=>{try{const selected=await api.choosePath(kind);if(selected)onChange(selected);setError('');}catch(e){setError(String(e));}}}><FolderOpen size={17}/></button></div>{hint&&<small className="field-hint">{hint}</small>}{error&&<small className="error-text">{error}</small>}</label>;
}
export function Wizard({data,config,setConfig,onOpen,onFinish,recents,busy,notify,initialStep=1}:{data:OpenProject|null;config:Config|null;setConfig:(c:Config)=>void;onOpen:(root:string,settings?:string,repository?:string,version?:MavenVersionSettings)=>Promise<void>;onFinish:()=>Promise<void>;recents:RecentProject[];busy:boolean;notify:(s:string)=>void;initialStep?:1|2}) {
  const [step,setStep]=useState(data?initialStep:0);
  const [root,setRoot]=useState(data?.project.rootDirectory??'');
  const [settings,setSettings]=useState(config?.maven.settingsPath??'');
  const [repository,setRepository]=useState(config?.maven.localRepository??'D:/m2');
  const [version,setVersion]=useState<MavenVersionSettings>({versionNumber:config?.maven.versionNumber??'',forceUpdate:config?.maven.forceUpdate??false});
  const [versionEdited,setVersionEdited]=useState(false);
  useEffect(()=>{if(config){setSettings(config.maven.settingsPath);setRepository(config.maven.localRepository);setVersion({versionNumber:config.maven.versionNumber??'',forceUpdate:config.maven.forceUpdate??false});setVersionEdited(false);}},[config?.rootPomPath]);
  const [loading,setLoading]=useState(false);
  const [prompt,setPrompt]=useState<'coveragePromptTemplate'|'repairPromptTemplate'>('coveragePromptTemplate');
  const run=async(action:()=>Promise<void>)=>{setLoading(true);try{await action();}catch(e){notify(e instanceof Error?e.message:String(e));}finally{setLoading(false);}};
  const agent=(patch:Partial<Config['agent']>)=>config&&setConfig({...config,agent:{...config.agent,...patch}});
  const maven=(patch:Partial<Config['maven']>)=>config&&setConfig({...config,maven:{...config.maven,...patch}});
  const steps=[['连接工程','项目与 Maven'],['选择范围','模块、包与类'],['补测策略','Agent 与提示词']];
  return <section className="wizard"><div className="page-title"><div><div className="eyebrow">NEW WORKSPACE</div><h1>配置你的补测工作区</h1><p>从项目开始，让每一次测试都向目标更近一步。</p></div><span className="subtle-badge">本地工作区</span></div>
    <div className="stepper">{steps.map(([title,subtitle],i)=><button disabled={i>step||busy} onClick={()=>setStep(i)} className={'step '+(i===step?'active':i<step?'done':'')} key={title}><span className="step-number">{i<step?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span><strong>{title}</strong><small>{subtitle}</small></span>{i<2&&<span className="step-line"/>}</button>)}</div>
    <fieldset disabled={busy||loading} className="wizard-fieldset"><motion.div key={step} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.18}}>
    {step===0&&<div className="setup-layout"><div className="panel setup-panel"><div className="panel-heading"><FolderOpen size={19}/><div><h2>连接本地工程</h2><p>选择包含根 pom.xml 的文件夹。</p></div></div><PathField label="项目根目录" value={root} onChange={setRoot} kind="project" placeholder="D:\Projects\your-project"/><PathField label="Maven settings.xml（可选）" value={settings} onChange={setSettings} kind="settings" placeholder="留空使用 Maven 默认配置"/><PathField label="本地 Maven 仓库" value={repository} onChange={setRepository} kind="repository" placeholder="D:/m2" hint="建议使用短路径，减少 ProGuard 流程中依赖参数过长导致的 CreateProcess error=206；留空沿用 settings。"/><MavenVersionFields value={version} onChange={v=>{setVersion(v);setVersionEdited(true);}}/><div className="inline-note"><FileCog size={16}/><p>已有的 Maven Wrapper 或系统 Maven 会自动识别。私服和仓库配置沿用你选择的 settings.xml。</p></div><div className="form-actions"><HoverBorderGradient onClick={()=>void run(async()=>{await onOpen(root,settings,repository,versionEdited?version:undefined);setStep(1);})} containerClassName="primary-gradient" className="gradient-content"><span>{loading?'正在扫描…':'扫描工程并继续'}</span><ArrowRight size={16}/></HoverBorderGradient></div></div>
    <aside className="setup-aside"><div className="outline-icon"><Layers3 size={28}/></div><h3>工程留在本机</h3><p>读取模块与源码目录，复用工程的构建环境。Agent 按你配置的服务处理代码。</p><div className="recent-list"><span className="eyebrow">最近打开</span>{recents.length?recents.map(r=><button key={r.rootPomPath} onClick={()=>void run(async()=>{await onOpen(r.rootPomPath);setRoot(r.rootPomPath.replace(/[\\/]pom.xml$/,''));setStep(1);})}><FolderOpen size={16}/><span><strong>{r.name}</strong><small>{r.rootPomPath}</small></span><ArrowRight size={14}/></button>):<p className="muted">打开的工程会出现在这里。</p>}</div></aside></div>}
    {step===1&&data&&config&&<><div className="section-heading"><div><h2>定义本次补测范围</h2><p>展开模块，直接勾选包和类。勾选纳入，取消排除，无需填写匹配规则。</p></div><div className="button-group"><button className="secondary small" onClick={()=>setConfig({...config,selectedModulePaths:data.project.modules.filter(m=>m.hasMainSources).map(m=>m.relativePath),scopes:[]})}>全选模块</button><button className="ghost small" onClick={()=>setConfig({...config,selectedModulePaths:[],scopes:[]})}>清空范围</button></div></div>
      <ScopeTree modules={data.project.modules} sources={data.sources} config={config} onChange={setConfig}/>
      <div className="scope-settings"><label className="field compact"><span>目标行覆盖率</span><div className="number-unit"><input type="number" min={1} max={100} value={config.coverage.lineThreshold} onChange={e=>setConfig({...config,coverage:{...config.coverage,lineThreshold:Number(e.target.value)}})}/><span>%</span></div></label><p className="field-hint">自动运行所选生产类所在包的测试。类的勾选决定覆盖率统计与补测范围。</p><div className="scope-summary"><strong>{selectedClassCount(config,data.sources)}</strong><span>已选择生产类<br/>配置随项目保存</span></div></div>
      {data.project.warnings.map(w=><p className="inline-warning" key={w}>{w}</p>)}
      <div className="wizard-actions"><button className="secondary" onClick={()=>setStep(0)}><ArrowLeft size={15}/>上一步</button><button className="primary" disabled={!selectedClassCount(config,data.sources)} onClick={()=>setStep(2)}>配置补测策略<ArrowRight size={15}/></button></div></>}
    {step===2&&config&&<><div className="strategy-grid"><div className="panel"><div className="panel-heading"><Bot size={19}/><div><h2>Agent 助手</h2><p>连接已经安装和配置好的编码助手。</p></div></div><label className="toggle-row"><span><strong>启用自动补测</strong><small>开启并保存后可启动“补测 → 验证”循环；仅运行基线无需开启</small></span><input type="checkbox" checked={config.agent.enabled} onChange={e=>agent({enabled:e.target.checked})}/></label><div className="form-grid"><label className="field"><span>编码助手</span><select value={config.agent.provider} onChange={e=>agent({provider:e.target.value})}><option value="hermes">Hermes</option><option value="opencode">OpenCode</option></select></label><label className="field"><span>模型（可选）</span><input value={config.agent.model} onChange={e=>agent({model:e.target.value})} placeholder="沿用助手默认模型"/></label></div><PathField label="助手程序（可选）" value={config.agent.executable} onChange={s=>agent({executable:s})} kind="agent" placeholder={'自动查找 '+config.agent.provider}/><label className="toggle-row"><span><strong>持续运行直到达标</strong><small>超时和执行失败后自动恢复；由你选择当前轮结束后停止或立即停止。</small></span><input type="checkbox" checked={config.agent.runUntilTarget!==false} onChange={e=>agent({runUntilTarget:e.target.checked})}/></label><div className="form-grid">{([['batchSize','每批处理类数',1,1000],['maxRounds','最多验证轮数',1,1000],['maxSameFailures',config.agent.runUntilTarget!==false?'重复失败后延长等待（次数）':'重复失败熔断',1,100],['timeoutMinutes','单轮 Agent 时限（分钟）',1,240]] as const).filter(([key])=>key!=='maxRounds'||config.agent.runUntilTarget===false).map(([key,label,min,max])=><label className="field" key={key}><span>{label}</span><input type="number" min={min} max={max} value={config.agent[key]} onChange={e=>agent({[key]:Number(e.target.value)})}/></label>)}<label className="field"><span>初始重试等待（秒）</span><input type="number" min={1} max={3600} value={config.agent.retryDelaySeconds??60} onChange={e=>agent({retryDelaySeconds:Number(e.target.value)})}/></label><label className="field"><span>最长重试等待（秒）</span><input type="number" min={config.agent.retryDelaySeconds??60} max={3600} value={config.agent.maxRetryDelaySeconds??600} onChange={e=>agent({maxRetryDelaySeconds:Number(e.target.value)})}/></label></div><p className="field-hint">连续故障逐步延长等待，成功后重置。单轮达到时限会保留测试改动，进入新一轮验证；未达标则继续补测。</p><label className="toggle-row"><span><strong>自动执行 Agent 操作</strong><small>允许助手自动修改测试；否则沿用 CLI 授权行为</small></span><input type="checkbox" checked={config.agent.autoApprove} onChange={e=>agent({autoApprove:e.target.checked})}/></label><p className="inline-note">默认仅修改所选模块的 src/test；请在独立分支或工作树运行，完成后查看代码差异。</p></div>
      <div className="panel prompt-panel"><div className="panel-heading"><Code2 size={19}/><div><h2>提示词编辑器</h2><p>分别定义补测与失败修复策略。</p></div></div><div className="tabs" role="tablist"><button role="tab" aria-selected={prompt==='coveragePromptTemplate'} className={prompt==='coveragePromptTemplate'?'selected':''} onClick={()=>setPrompt('coveragePromptTemplate')}>覆盖率补充</button><button role="tab" aria-selected={prompt==='repairPromptTemplate'} className={prompt==='repairPromptTemplate'?'selected':''} onClick={()=>setPrompt('repairPromptTemplate')}>失败用例修复</button></div><textarea className="prompt-editor" aria-label={prompt==='coveragePromptTemplate'?'覆盖率补充提示词':'失败修复提示词'} value={config.agent[prompt]} onChange={e=>agent({[prompt]:e.target.value})} spellCheck={false}/><div className="editor-footer"><span>保留模板中的占位符，运行时自动填充上下文</span><span>{config.agent[prompt].length} 字符</span></div></div></div>
      <details className="panel advanced"><summary><SlidersHorizontal size={16}/><strong>高级配置</strong><span>JDK、Maven、Provider 与额外参数</span></summary><div className="advanced-body"><div className="form-grid"><PathField label="目标工程 JDK（可选）" value={config.maven.javaHome} onChange={s=>maven({javaHome:s})} kind="jdk" placeholder="沿用 JAVA_HOME"/><PathField label="Maven 程序（可选）" value={config.maven.executable} onChange={s=>maven({executable:s})} kind="maven" placeholder="自动识别 Maven"/><label className="field"><span>激活 Profiles（逗号分隔）</span><input value={config.maven.profiles.join(',')} onChange={e=>maven({profiles:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><label className="field"><span>JaCoCo 版本</span><input value={config.coverage.jacocoVersion} onChange={e=>setConfig({...config,coverage:{...config.coverage,jacocoVersion:e.target.value}})}/></label><label className="field"><span>{config.agent.provider==='hermes'?'Hermes Provider':'OpenCode Agent'}</span><input value={config.agent.provider==='hermes'?config.agent.hermesProvider:config.agent.opencodeAgent} onChange={e=>agent(config.agent.provider==='hermes'?{hermesProvider:e.target.value}:{opencodeAgent:e.target.value})}/></label><label className="field"><span>Maven 额外参数（一行一个）</span><textarea value={config.maven.extraArgs.join('\n')} onChange={e=>maven({extraArgs:e.target.value.split('\n')})}/></label><label className="field"><span>Agent 额外参数（一行一个）</span><textarea value={config.agent.extraArgs.join('\n')} onChange={e=>agent({extraArgs:e.target.value.split('\n')})}/></label></div><label className="toggle-row"><span>首轮先执行 Maven install 预构建（跳过测试）</span><input type="checkbox" checked={config.maven.preInstall} onChange={e=>maven({preInstall:e.target.checked})}/></label></div></details>
      <div className="wizard-actions"><button className="secondary" onClick={()=>setStep(1)}><ArrowLeft size={15}/>上一步</button><div className="button-group"><label className="config-name"><span>配置名称</span><input aria-label="配置名称" value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></label><button className="primary" onClick={()=>void run(onFinish)}><Save size={15}/>{loading?'正在保存…':'保存并进入看板'}<ArrowRight size={15}/></button></div></div></>}
    </motion.div></fieldset>
  </section>;
}
